# Generated by Django 5.0.6 on 2024-08-16 08:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinglanguages',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.languages'),
        ),
        migrations.AlterField(
            model_name='listinglanguages',
            name='proficiency',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
