# Generated by Django 5.0.6 on 2024-08-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listinglanguages_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingspecialization',
            old_name='end_date',
            new_name='date_issued',
        ),
        migrations.RenameField(
            model_name='listingspecialization',
            old_name='start_date',
            new_name='expiry_date',
        ),
    ]
