# Generated by Django 5.0.6 on 2024-08-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listingspecialization_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingaffiliationsandmemberships',
            old_name='end_date',
            new_name='date_issued',
        ),
        migrations.RenameField(
            model_name='listingaffiliationsandmemberships',
            old_name='start_date',
            new_name='expiry_date',
        ),
        migrations.AddField(
            model_name='listingaffiliationsandmemberships',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=20, null=True),
        ),
    ]
