# Generated by Django 5.0.6 on 2024-09-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listingexperience_years_of_experience'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listingservices',
            unique_together={('listing', 'service')},
        ),
    ]
