# Generated by Django 5.0.6 on 2024-08-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_degree_listingeducationalbackground_institute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingspecialization',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='listingspecialization',
            name='status',
        ),
        migrations.AddField(
            model_name='listingexperience',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingexperience',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingexperience',
            name='duties',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='listingexperience',
            name='skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listingexperience',
            name='still_employed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('Doctor', 'Doctor'), ('Locum', 'Locum'), ('Practice', 'Practice'), ('Nurse', 'Nurse')], max_length=50, null=True),
        ),
    ]
