# Generated by Django 5.0.6 on 2024-08-18 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listingspecialization_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingexperience',
            name='years_of_experience',
            field=models.IntegerField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
