# Generated by Django 5.0.6 on 2024-08-18 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listingexperience_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingexperience',
            name='years_of_experience',
            field=models.IntegerField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
