# Generated by Django 5.0.6 on 2024-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_days_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
