# Generated by Django 5.0.6 on 2024-08-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_days_date_created_days_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='name',
            new_name='day',
        ),
    ]
