# Generated by Django 5.0.6 on 2024-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_rename_name_days_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsavailability',
            name='average_wait_time',
            field=models.IntegerField(blank=True, help_text='Expressed in hours as an Integer', max_length=50, null=True),
        ),
    ]
