# Generated by Django 5.0.6 on 2024-08-18 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_appointmentsavailability_average_wait_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsavailability',
            name='average_wait_time',
            field=models.IntegerField(blank=True, help_text='Expressed in hours as an Integer', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
