# Generated by Django 5.0.6 on 2024-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listingservices_availability'),
        ('utils', '0002_rename_date_create_services_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingservices',
            name='service',
        ),
        migrations.AddField(
            model_name='listingservices',
            name='service',
            field=models.ManyToManyField(to='utils.services'),
        ),
    ]
