# Generated by Django 5.0.6 on 2024-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_listingservices_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingservices',
            name='is_active',
            field=models.BooleanField(default=True, max_length=6),
        ),
    ]
