# Generated by Django 5.0.6 on 2024-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_listingservices_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingservices',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
