# Generated by Django 5.0.6 on 2024-08-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='date_create',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='accessibility',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='accessibility',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
