# Generated by Django 5.0.1 on 2024-02-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utils',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
