# Generated by Django 5.0.6 on 2024-08-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_rename_date_create_services_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibility',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='accessibility',
            name='pricing',
        ),
    ]
