# Generated by Django 5.0.6 on 2024-08-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_listingservices_is_active'),
        ('utils', '0003_remove_accessibility_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibility',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
