# Generated by Django 5.0.6 on 2024-08-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_accessibility_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
    ]
